#!/bin/bash

_get_ziplink () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL211aGFtbWVkZnVya2FuL1VuaUJvcmcvYXJjaGl2ZS9yZWZzL2hlYWRzL21hc3Rlci56aXA=" | base64 -d
}

_set_bot () {
    local zippath
    zippath="kopp.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    kopath=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $kopath
    echo "    Starting Bot    "
    python3 -m stdborg
}

_set_bot
